# Generated by Django 4.1.5 on 2023-03-07 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votings",
            name="finish",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 7, 3, 9, 54, 884991)
            ),
        ),
        migrations.AlterField(
            model_name="votings",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 7, 3, 9, 54, 884991)
            ),
        ),
    ]
