# Generated by Django 4.1.5 on 2023-02-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="time",
            field=models.DateTimeField(default="16/09/2002 00:00:00"),
        ),
    ]
