# Generated by Django 4.1.5 on 2023-02-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidates",
            old_name="file",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="votings",
            old_name="file",
            new_name="parlament_image",
        ),
    ]
