# Generated by Django 4.1.5 on 2023-02-20 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_alter_customuser_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="VotingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate", models.CharField(max_length=255)),
                ("vote", models.CharField(default="1", max_length=5)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="time",
            field=models.DateTimeField(default="2002-09-16 00:00:00"),
        ),
    ]
