# Generated by Django 4.1.5 on 2023-01-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_votings_faculty_image_votings_parlament_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votings',
            name='faculty_image',
        ),
        migrations.AddField(
            model_name='goals',
            name='candidate_goalsno',
            field=models.IntegerField(default=0),
        ),
    ]
