# Generated by Django 4.1.5 on 2023-03-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0003_votingtime_alter_customuser_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="time",
            field=models.CharField(default="2002-09-16 00:00:00", max_length=50),
        ),
    ]
