# Generated by Django 4.1.5 on 2023-03-06 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0007_alter_votings_finish_alter_votings_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votings",
            name="finish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 6, 23, 36, 38, 597974, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="votings",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 6, 23, 36, 38, 597974, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="votingtime",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 6, 23, 36, 38, 597974, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
